import React from 'react'
import Container from '../components/Container'
import getAllBlogs from '@/lib/getAllBlogs'
import Link from 'next/link';

export const metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};

export default async function getAllBlog() {
  const posts = await getAllBlogs();
//  console.log(posts);


  return (
   
    <Container>
      <div className="mt-4">
        <h5 className='bg-blue-800 text-amber-50 p-3 mb-4'>All blog post From Api...........</h5>
        <ul>
          {posts.map((post) => (
            <li key={post.id}>
             <Link href={`/posts/${posts.id}`}>{posts.title}</Link>
              </li>
          ))}
        </ul>
      </div>
    </Container>
  )
}
