import React from 'react'
import Container from '../components/Container'

export const metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};

export default function Blog() {
  return (
   <Container>
        <div className="mt-4">Blog Page</div>
    </Container>
  )
}
