import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";



export const metadata = {
  title: "EcomerceApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased">

      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
