import React from 'react'
import Container from '../components/Container'


export const metadata = {
  title: "ContactUs",
  description: "Generated by create next app",
};

export default function ContactUs() {
  return (
    <Container>

    <div className="mt-4">
        
         Contact US
         
         
   </div>

    </Container>
  )
}
