import React from 'react'
import Container from '../components/Container'


export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};


export default function Shop() {
  return (

    <Container>
         <div className='mt-4'>Shop page</div>
    </Container>

  )
}
