import React from 'react'
import Container from '../components/Container'
import ProductCard from '../components/ProductCard'



export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};


export default function Product() {
  return (
    <Container>
     <div className="mt-4">
          <ProductCard />
    </div>
   </Container>
    
  )
}
